version: '3.8'

services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  # add more external services

volumes:
  postgres-data:
