version: '3.8'

services:
  app:
    image: ghcr.io/corp-momenti/docker-images/momenti-elixir-dev:33b1b287fe21d6d11c600dfc210662378f593e6c
    volumes:
      - ..:/home/vscode/workspace:cached
      - build:/home/vscode/workspace/_build
      - deps:/home/vscode/workspace/deps
      - config:/home/vscode/.config
      - extensions:/home/vscode/.vscode-server/extensions
      - local:/home/vscode/.local
    command: sleep infinity
    init: true
    privileged: true
    network_mode: service:traefik
    environment:
      WARNINGS_AS_ERRORS: 'false'

volumes:
  config:
  build:
  deps:
  extensions:
  local:
